FROM linuxserver/qbittorrent:101
# https://github.com/linuxserver/docker-qbittorrent/blob/101/Dockerfile

# Add preferences to show in Organizr (https://github.com/causefx/Organizr/issues/838)
COPY qBittorrent.conf /defaults